### ISSUE TITLE
How to run compiled model on GPU?

### ISSUE THREAD

**Issue by zhangxj19** [onnx/onnx-mlir#1229]
Recently I'm trying to run the onnx-mlir-compiled model on GPU.
Here is my idea: 
krnl/affine/std -> memref/affine/std -> GPU Dialect ->LLVM IR -> NNVM -> PTX
I have no idea whether it will work. If not, could you please share me some of your points? Thank you very much.

**Comment by AlexandreEichenberger** [comment]
Two thoughts: 

1. One approach uses calls to an optimized library. That is the approach we have used internally (and we are in the process of externalizing, see current PRs). So we go ONNX to KRNL (for CPU running ops) or ZHigh (dialect that eventually turns into calls into the optimized library for our Z AI accelerator). There is a lot of work on the accelerator side because it uses a special data format. You could use a similar approach to transform ONNX operations into library calls to a GPU opt library.
2. wait until we lower to Affine and then go your/MLIR way to GPUs.

Note that there is an effort lead by Arm/Google to use ONNX to TOSA. There is apparently a prototype but no PR yet in the code.

**Comment by zhangxj19** [comment]
Thanks for information!
