### ISSUE TITLE
cruntime does not exist

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#147]
I got the following error when doing `cmake ..` with the latest commit:
```bash
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Found PythonInterp: /gsa/jpngsa/home/t/u/tungld/dl/anaconda2/envs/python3.6/bin/python (found version "3.6.9")
-- pybind11 v2.4.dev4
-- INCLUDE_ONNX_ML Dialect TRUE
CMake Error at src/CMakeLists.txt:69 (install):
  install TARGETS given target "cruntime" which does not exist in this
  directory.
```

Any suggestion to resolve this error?

**Comment by tjingrant** [comment]
Looks like maybe it's because cruntime is created in a subdirectory?
https://stackoverflow.com/questions/34443128/cmake-install-targets-in-subdirectories

Anyhow, I can certainly move the install command down to the `src/Runtime` subdirectory.

**Comment by gongsu832** [comment]
The problem is most likely due to the cached contents under build directory. cmake often fails with all kinds of problems when you rerun it with cached contents that get out of sync with updated source. It should be enough to just rm CMakeCache.txt before running cmake but I never bothered and just do "rm -rf *".

**Comment by tungld** [comment]
Thanks @gongsu832 and @tjingrant for suggesting solutions! I created a PR to resolve the issue.
