### ISSUE TITLE
Implement operators in separated functions

### ISSUE THREAD

**Issue by ljppro** [onnx/onnx-mlir#168]
Hi,

It seems that when onnx-mlir translate the onnx model into MLIR, it will fuse all operators into a single main_graph function. Can I change this behavior by implement each operator into a separated a function? That is, a function for an operator?

Many thanks!

**Comment by tjingrant** [comment]
Hello @ljppro is there any benefit in doing so? If you can walk me through the motivations/context, I may be able to give you a better answer to your question.

**Comment by ljppro** [comment]
Hi, @tjingrant,

I think it would be benefit if we want to schedule the operators into different computing devices, for example, to implement the GPipe or Pipedream. At least it would be better to provide an option to the users if they want to do some research here.

Many thanks!

**Comment by ljppro** [comment]
Hi @tjingrant,

And another argument is in the NN model these operators are separated and ONNX is just to exchanging the model between different frameworks. So the model exported by ONNX-MLIR should be the same to the original model. With fusing all operators into one, the ONNX-MLIR has already introduced the runtime scheduling here, not just a static model.
Do you think it is reasonable?

Many thanks!

**Comment by tjingrant** [comment]
@ljppro I fail to see the necessity of having each operator lowered to an individual function to the ability to perform device placement optimization using onnx-mlir as an infrastructure.

Couldn't you operate on ONNX IR (listed below for mnist) and move operations into separate functions representing the execution context of different devices using a custom transformation pass? Then when you lower, the affine dialect operations will also appear under different functions.

```
module {
  func @main_graph(%arg0: tensor<1x784xf32>) -> tensor<1x10xf32> {
    %cst = constant unit
    %0 = "onnx.Reshape"(%arg0, %cst) {shape = dense<[-1, 1, 28, 28]> : tensor<4xi32>} : (tensor<1x784xf32>, none) -> tensor<1x1x28x28xf32>
    %1 = "onnx.Constant"() : () -> tensor<5x5x1x32xf32>
    %2 = "onnx.Constant"() : () -> tensor<32xf32>
    %3 = "onnx.Transpose"(%1) {perm = [3, 2, 0, 1]} : (tensor<5x5x1x32xf32>) -> tensor<32x1x5x5xf32>
    %4 = "onnx.Pad"(%0, %cst, %cst) {constant_value = dense<0.000000e+00> : tensor<1xf32>, mode = "constant", pads = dense<[0, 0, 2, 2, 0, 0, 2, 2]> : tensor<8xi64>} : (tensor<1x1x28x28xf32>, none, none) -> tensor<1x1x32x32xf32>
    %5 = "onnx.Conv"(%4, %3, %cst) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : i64, kernel_shape = [5, 5], pads = [0, 0, 0, 0], strides = [1, 1]} : (tensor<1x1x32x32xf32>, tensor<32x1x5x5xf32>, none) -> tensor<1x32x28x28xf32>
    %6 = "onnx.Unsqueeze"(%2) {axes = [1, 2]} : (tensor<32xf32>) -> tensor<32x1x1xf32>
    %7 = "onnx.Add"(%5, %6) : (tensor<1x32x28x28xf32>, tensor<32x1x1xf32>) -> tensor<1x32x28x28xf32>
    %8 = "onnx.Relu"(%7) : (tensor<1x32x28x28xf32>) -> tensor<1x32x28x28xf32>
    %9 = "onnx.MaxPoolSingleOut"(%8) {auto_pad = "NOTSET", dilations = [1, 1], kernel_shape = [2, 2], pads = [0, 0, 0, 0], strides = [2, 2]} : (tensor<1x32x28x28xf32>) -> tensor<1x32x14x14xf32>
    %10 = "onnx.Constant"() : () -> tensor<5x5x32x64xf32>
    %11 = "onnx.Constant"() : () -> tensor<64xf32>
    %12 = "onnx.Transpose"(%10) {perm = [3, 2, 0, 1]} : (tensor<5x5x32x64xf32>) -> tensor<64x32x5x5xf32>
    %13 = "onnx.Pad"(%9, %cst, %cst) {constant_value = dense<0.000000e+00> : tensor<1xf32>, mode = "constant", pads = dense<[0, 0, 2, 2, 0, 0, 2, 2]> : tensor<8xi64>} : (tensor<1x32x14x14xf32>, none, none) -> tensor<1x32x18x18xf32>
    %14 = "onnx.Conv"(%13, %12, %cst) {auto_pad = "NOTSET", dilations = [1, 1], group = 1 : i64, kernel_shape = [5, 5], pads = [0, 0, 0, 0], strides = [1, 1]} : (tensor<1x32x18x18xf32>, tensor<64x32x5x5xf32>, none) -> tensor<1x64x14x14xf32>
    %15 = "onnx.Unsqueeze"(%11) {axes = [1, 2]} : (tensor<64xf32>) -> tensor<64x1x1xf32>
    %16 = "onnx.Add"(%14, %15) : (tensor<1x64x14x14xf32>, tensor<64x1x1xf32>) -> tensor<1x64x14x14xf32>
    %17 = "onnx.Relu"(%16) : (tensor<1x64x14x14xf32>) -> tensor<1x64x14x14xf32>
    %18 = "onnx.MaxPoolSingleOut"(%17) {auto_pad = "NOTSET", dilations = [1, 1], kernel_shape = [2, 2], pads = [0, 0, 0, 0], strides = [2, 2]} : (tensor<1x64x14x14xf32>) -> tensor<1x64x7x7xf32>
    %19 = "onnx.Constant"() : () -> tensor<3136x1024xf32>
    %20 = "onnx.Constant"() : () -> tensor<1024xf32>
    %21 = "onnx.Reshape"(%18, %cst) {shape = dense<[-1, 3136]> : tensor<2xi32>} : (tensor<1x64x7x7xf32>, none) -> tensor<1x3136xf32>
    %22 = "onnx.Gemm"(%21, %19, %20) {alpha = 1.000000e+00 : f32, beta = 1.000000e+00 : f32, transA = 0 : i64, transB = 0 : i64} : (tensor<1x3136xf32>, tensor<3136x1024xf32>, tensor<1024xf32>) -> tensor<1x1024xf32>
    %23 = "onnx.Relu"(%22) : (tensor<1x1024xf32>) -> tensor<1x1024xf32>
    %24 = "onnx.Constant"() : () -> tensor<1024x10xf32>
    %25 = "onnx.Constant"() : () -> tensor<10xf32>
    %26 = "onnx.Gemm"(%23, %24, %25) {alpha = 1.000000e+00 : f32, beta = 1.000000e+00 : f32, transA = 0 : i64, transB = 0 : i64} : (tensor<1x1024xf32>, tensor<1024x10xf32>, tensor<10xf32>) -> tensor<1x10xf32>
    return %26 : tensor<1x10xf32>
  }
  "onnx.EntryPoint"() {func = @main_graph, numInputs = 1 : i32, numOutputs = 1 : i32} : () -> ()
}
```

> And another argument is in the NN model these operators are separated and ONNX is just to exchanging the model between different frameworks. So the model exported by ONNX-MLIR should be the same to the original model.

What you said is true of ONNX, but ONNX-MLIR is not a model converter (sorry for the confusing naming choice, we have little freedom over the project name). ONNX-MLIR represents ONNX model within MLIR framework, and provide you with multiple levels of IR which you can use as starting point of your own experiments/research.

> With fusing all operators into one, the ONNX-MLIR has already introduced the runtime scheduling here, not just a static model.

Why does emitting all operators under one function introduce more runtime schedule than emitting operators under individual functions? 

Let me have a guess of the real issue you're facing - are you worried that in the IR you obtained at the lower level of abstraction, say the affine dialect IR, it becomes nearly impossible to separate your models into smaller pieces so that they can be mapped to different devices? If that's the case, then the solution is simply to break down the model IR at a higher-level of abstraction first (say, ONNX IR level as shown above), then invoke the onnx-mlir lowering facilities on the IR module containing multiple functions representing pieces of models.

If my guess is wrong or you'd like to chat about this issue more, I'm happy to talk about it with you for more details, and please feel free to send me emails to the address listed in my Github profile to schedule a chat.

**Comment by ljppro** [comment]
Hi, @tjingrant,
Yes, this is exactly what the issues. We use onnx-mlir just want to lower part of the onnx model into our proprietary devices by the LLVM backend. And thanks for your solution, I think it's a great help.
