### ISSUE TITLE
check-onnx-backend link error

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx-mlir#175]
Any idea about the fix?

`
make check-onnx-backend

...
/usr/bin/ld: cannot find -lEmbeddedDataLoader
/usr/bin/ld: cannot find -lcruntime
collect2: error: ld returned 1 exit status
g++ -shared -fPIC temp_model.o /tmp/packed_const-a52592.tmp.o -o temp_model.so -lEmbeddedDataLoader -lcruntime
Command execution failed.
UNREACHABLE executed at /home/chentong/onnx-mlir/src/MainUtils.cpp:94!
Esssssssss/usr/bin/ld: cannot find -lEmbeddedDataLoader
/usr/bin/ld: cannot find -lcruntime
collect2: error: ld returned 1 exit status
...
`

**Comment by tjingrant** [comment]
The solution is to do a `make install`. But I'm working on it to provide a more reasonable explanation or improve the workflow so that we don't have to worry about it in the future..

**Comment by AlexandreEichenberger** [comment]
Tong,
 
the install worked wonders for me, even after deleting and rebuilding the build dir from scratch. Let's add the solution to the README (if still applicable) once Tian has finished working on what he wanted to tweak.
Alexandre-----------------------------------------------------------------------------------------------------Alexandre Eichenberger, Principal RSM, Advanced Compiler Technologies- research: compiler optimization (OpenMP, GPU, SIMD)- info: alexe@us.ibm.com http://www.research.ibm.com/people/a/alexe- phone: 914-945-1812 (work), 914-312-3618 (cell)
 
 
----- Original message -----From: Tian Jin <notifications@github.com>To: onnx/onnx-mlir <onnx-mlir@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [EXTERNAL] Re: [onnx/onnx-mlir] check-onnx-backend link error (#175)Date: Sun, Jun 21, 2020 10:51 AM 
 
The solution is to do a make install. But I'm working on it to provide a more reasonable explanation or improve the workflow so that we don't have to worry about it in the future..

**Comment by gongsu832** [comment]
The basic problem is that the library search path needs to be specified by -L... since it's not in a standard place unless you've done "make install". In fact, I see onnx-mlir checks an env var RUNTIME_DIR (probably better named ONNX_MLIR_RUNTIME_DIR). So if you set it to where all the libraries are (typically .../build/lib) then you shouldn't have such linkage problem.

But I find that having to do a "make install" is cumbersome for development purpose. Perhaps a reasonable solution is for onnx-mlir to find its execution path, e.g., /foo/bar/whatever/bin/onnx-mlir, and if the path ends with "bin" (most likely the case), then adds -L/foo/bar/whatever/lib to the linkage command. This should allow onnx-mlir --EmitLib (and maybe others in the future) to work without having to do a "make install".

**Comment by chentong319** [comment]
There is no link error with the new version, even without make install. But I got runtime error:

ERROR: test_abs_cpu (__main__.OnnxBackendNodeModelTest)
Traceback (most recent call last):
  File "/autofs/home/chentong/upstream-onnx-mlir/third_party/onnx/onnx/backend/test/runner/__init__.py", line 248, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/autofs/home/chentong/upstream-onnx-mlir/third_party/onnx/onnx/backend/test/runner/__init__.py", line 278, in run
    prepared_model = self.backend.prepare(model, device)
  File "/home/chentong/onnx-mlir/build/test/backend/test.py", line 95, in prepare
    "_dyn_entry_point_main_graph")
  File "/home/chentong/onnx-mlir/build/test/backend/test.py", line 50, in __init__
    super().__init__(path, entry_point)
RuntimeError: Cannot open library: libcruntime.so: cannot open shared object file: No such file or directory

**Comment by gongsu832** [comment]
What platform is this on? Linux? From the error message your home directory shows up sometimes as `/home/chentong` but sometimes as `/autofs/home/chentong`. That might confuse the python script. `make VERBOSE=1 check-onnx-backend` might give more clue.

**Comment by chentong319** [comment]
on a PowerPC Red Hat Enterprise Linux Server release 7.6 system.
With VERBOSE=1, I got extra info on compilation, such as:

ld -r -b binary -o /tmp/packed_const-9586b3.tmp.o /tmp/packed_const-9586b3.tmp
objcopy --redefine-sym _binary__tmp_packed_const_9586b3_tmp_start=_binary_param_bin_start /tmp/packed_const-9586b3.tmp.o
objcopy --redefine-sym _binary__tmp_packed_const_9586b3_tmp_end=_binary_param_bin_end /tmp/packed_const-9586b3.tmp.o
llc -filetype=obj -relocation-model=pic -o temp_model.o temp_model.bc
g++ -shared -fPIC /tmp/packed_const-9586b3.tmp.o temp_model.o -o temp_model.so -L/autofs/home/chentong/onnx-mlir/build/lib64 -lEmbeddedDataLoader -lcruntime
Shared library temp_model.so has been compiled.

**Comment by gongsu832** [comment]
Where is the error message when VERBOSE=1? Can you attach the whole log? Did you check why your home directory shows up differently? It looks like you are using RHEL autofs? Your home directory showing up with different path names typically means there are symlinks or hard links involved. It can cause trouble with apps that don't resolve them properly. If possible, I'd try the build in a directory that's not managed by autofs.

**Comment by chentong319** [comment]
The reason for failure turned out to be that I have to build from a new directory: "make clean" is not enough.
