### ISSUE TITLE
Refactor Dialect/ONNX dir

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#1802]
I can't help but see that the ONNXOps.cpp is huge (6k lines) and at the same time we have almost one file per op for shape inference.

Would it make sense to rename the "ShapeInference" dir as "OpSupport" and migrate the code of each op(or family, e.g. for unary and binary... others too maybe) from ONNXOps.cpp (namely custom builders, verifiers,,,) into the current ShapeInference/<<Op>>.cpp.  We could have the same sub directory structure as for Conversion/ONNXToKrnl, for example, or just the current flat structure.

It would make the code more tidy (all basic code for an op in one file).

It would not change how libs are done (currently ONNXOps.cpp and all shape inference is dumped in the same lib).

What do you guys think? @chentong319 @tungld and any other interested in this.

**Comment by tungld** [comment]
@AlexandreEichenberger it makes sense. We have a .cpp for each op or each category, then put all necessary code that defines the op in it. This also reduces conflicts when multiple PRs are modifying the same large ONNNXOps.cpp.

**Comment by AlexandreEichenberger** [comment]
@hpmorgan @mikeessen Are one of you interested in doing a bit of refactoring to get more familiar with the code?
Ideally, once this is started, it would need to go down fast as code is moved (and if it last too long, there will be conflicts that would need time to fix individually).

**Comment by chentong319** [comment]
Agree on the restructuring of code.
To my understanding, we want to put all member functions of each ONNX Op into a separate file. The member functions include ShapeInference, verifier, constructor, data flow interface, and fold. There is one outliner, canonicalization.

**Comment by sorenlassen** [comment]
I like this idea.

For some ops we could just have a .cpp implementation of verify() and inferShapes() and for others we could add a .hpp for helper functions that we want to export.

For example, ONNXEinsumOpHelper.{hpp,cpp} could move into OpSupport/Einsum.{hpp,cpp}.

There are some helper functions that today are exported in ONNXShapeHelper.hpp which would be nice to move into per-operation header files, e.g. getDataShapeBounds and computeSelectedData. We could also move things like ONNXSliceOpShapeHelper to OpSupport/Slice.hpp.

I'd also suggest that we remove OpsWithHelpers from gen_onnx_mlir.py and ONNXOps.td.inc and make things like v_final helper functions instead of op methods.

**Comment by AlexandreEichenberger** [comment]
Thanks for the feedback to all, and yes, @sorenlassen,  I like your suggestion that helper functions would go down into the subdirectories, sometimes some functions are used for each of the "conv/pool"... and then they can go into the `ops/NN` directory in a common header/cpp file. And when they are not common to multiple files, they can go in their own header/cpp file.

> I'd also suggest that we remove OpsWithHelpers from gen_onnx_mlir.py and ONNXOps.td.inc and make things like v_final helper functions instead of op methods.

I will let @chentong319 chime in on this, as I suspect he added these since it target loop and scan.

**Comment by chentong319** [comment]
This issue is about structure of files.
Change of OpWithHelpers is about what should be defined as a member function and what should be defined as helper function. This is a general topic in OO design. v_final and v_initial could be defined with helper function, like v_final(Operation *op) or v_final(T operation). We can review other functions defined with Op, too. For example, those functions for importing the model can be replaced with a static map indexed with ONNX Op type. Also, MLIR likes to define named interface other than just define functions explicitly in an Op. In this sense, we may need to do something with v_final and v_initial.
Since ONNXOpsHelper contains some common utilities for ONNX dialect, I think it should be kept. It is not easy to handle the include files if the helper functions are split by ONNX Op.

**Comment by sorenlassen** [comment]
> It is not easy to handle the include files if the helper functions are split by ONNX Op.

I agree it has been difficult to handle include files and I hope the new OpSupport/ source code structure can make it easier.

The problem with the code generation with gen_onnx_mlir.py is that it makes the edit/compile/codereview cycle harder. Moreover, the way the python and C++ source code play together is difficult for newcomers to understand.

(We could also consider restructuring gen_onnx_mlir.py to make it easier to understand and maintain. If anyone is interested in that please let me know. I think there are some good ways to make it better if someone has time to take it on.)

**Comment by chentong319** [comment]
If we define interface/trait for ONNX Op, we do not need to add C++ source code in gen_onnx_mlir.py, Just like the shape inference interface. 
I agree that we should restructure gen_onnx_mlir.py to have an easier way to attach properties to ONNX Op. We can target at just keep the interface and removing most of the code from gen_onnx_mlir.py, if that's the direction we'd like to go after.

**Comment by AlexandreEichenberger** [comment]
#1828 implement the reorg, or at least part of it.

**Comment by sorenlassen** [comment]
@AlexandreEichenberger I'm closing this issue since ONNXOps.cpp is no longer huge

my helper functions idea hasn't been solved but I don't think we need this issue to track that
