### ISSUE TITLE
Unable to compile ResNet50 model from Keras

### ISSUE THREAD

**Issue by cjvolzka** [onnx/onnx-mlir#1844]
Attempting to compile example ResNet50 model from Keras using `--O3 --EmitLib --mtriple=s390x-ibm-loz --mcpu=z14 ResNet50.onnx --onnx-op-stats TXT -v` fails with:

```
Operations encountered:
-----------------------
  func.func             , 1
  func.return           , 1
  onnx.Add              , 46
  onnx.Concat           , 59
  onnx.Constant         , 122
  onnx.Conv             , 23
  onnx.Dim              , 29
  onnx.Gemm             , 1
  onnx.MatMul           , 30
  onnx.MaxPoolSingleOut , 1
  onnx.Pad              , 1
  onnx.ReduceMean       , 1
  onnx.Relu             , 49
  onnx.Reshape          , 59
  onnx.Softmax          , 1
  onnx.Squeeze          , 1
  onnx.Transpose        , 1
onnx-mlir: /build/llvm-project/mlir/lib/Dialect/Affine/IR/AffineOps.cpp:2723: static void mlir::AffineLoadOp::build(mlir::OpBuilder&, mlir::OperationState&, mlir::Value, mlir::AffineMap, mlir::ValueRange): Assertion `map.getNumInputs() == mapOperands.size() && "inconsistent index info"' failed.
```

At a glance, I'm not sure why it is failing. I used the most recent versions of tensorflow and tf2onnx for Mac (x86). Looking at the netron graphy of the model, I don't see any Ops that jump out as unsupported.

Note: I tried this with `main` and the 0.3.1 and 0.3.0 releases and got the same result.

To create and save the model: (requires tensorflow)
```
import tensorflow
tensorflow.keras.applications.resnet50.ResNet50(weights='imagenet').save("ResNet50")
```
To convert to ONNX: (requires tf2onnx)
```
python -m tf2onnx.convert --saved-model ResNet50/ --output ResNet50.onnx
```

**Comment by chentong319** [comment]
Can you use gdb to locate where that error occurred? Or attach your ResNet50.onnx here.

**Comment by cjvolzka** [comment]
Is there someplace I can upload the model? It's too large to attach to github directly.

**Comment by xlindo** [comment]
Similar to https://github.com/onnx/onnx-mlir/issues/1571

**Comment by chentong319** [comment]
I did some investigation with Mike today. Here is the outcome:
This krnl.load caused the assertion error when krnl is lowered to affine:
```
%123 = krnl.load %71[] : memref<1xf32>
```
The reason is that there is no index  for  %71 when the type is 1-D memref.
I traced back to the output of `--EmitONNXBasic` and this operation came from:
```
    %113 = onnx.Constant dense<0.000000e+00> : tensor<1xf32>
    %114 = "onnx.Pad"(%112, %106, %113) {mode = "constant", onnx_node_name = "resnet50/pool1_pad/Pad"} : (tensor<*xf32>, tensor<8xi64>, tensor<1xf32>) -> tensor<*xf32>
```
The  third parameter `%113`. The onnx operation document said that 
```
constant_value (optional, non-differentiable) : T
(Optional) A scalar value to be used if the mode chosen is `constant` (by default it is 0, empty string or False).
```
It is a scalar, and should have  type `tensor<f32>`, instead of `tensor<1xf32>`.
Not sure whether the error came from the model or the recent change of constant.
@sorenlassen Since this issue was opened back on Nov 8,2022, the new disposable constant was not added yet. Right?
@mikeessen You can check whether the type info in the onnx model is correct or not.

A workaround solution: When the third parameter of Pad lowered from onnx to krnl, give 0 as index if the type is tensor<1xf32>, though it is supposed to be a scalar.

**Comment by sorenlassen** [comment]
> Since this issue was opened back on Nov 8,2022, the new disposable constant was not added yet. Right?

right, it was added Jan 11, 2023 in PR #1874

**Comment by mikeessen** [comment]
> 

@chentong319 Please point me to the code in onnx-mlir that generates %113 and %114 from the onnx file?   This should help to see why a type tensor<f32>, instead of tensor<1xf32> is generated.

**Comment by chentong319** [comment]
onnx-mlir/src/Conversion/ONNXToKrnl/Tensor/Pad.cpp, line 75
```
cValue = create.krnl.load(constantValue, {});
```

**Comment by cjvolzka** [comment]
Thanks @mikeessen and @chentong319 for the fix!
