### ISSUE TITLE
Upgrade Python from 3.9/3.10 to 3.11

### ISSUE THREAD

**Issue by hamptonm1** [onnx/onnx-mlir#1935]
`onnx` is currently supporting python version 3.11. Is this something we also want to upgrade to? So that we can be fully in sync with what the `onnx` community is doing? Let me know your thoughts please. Thank you!

Currently macOS build is using python 3.10 and everything else is using 3.9 from my understanding. 

FYI- @AlexandreEichenberger @gongsu832 @chentong319

**Comment by gongsu832** [comment]
What version of python we use is gated by the available versions on the Linux distributions we use for our docker images. Ubuntu Focal (dev image) has 3.8 and RHEL ubi8 (user image) has 3.9 so those are what we use. I plan to upgrade Focal to Jammy and that will bump python up to 3.10. But upgrading ubi8 to ubi9 is problematic at this point since ubi9 apparently requires z14 and above.

Keep in sync with other related projects such as onnx and/or llvm is desirable but ultimately it comes down to each project's own requirements.

**Comment by hamptonm1** [comment]
> What version of python we use is gated by the available versions on the Linux distributions we use for our docker images. Ubuntu Focal (dev image) has 3.8 and RHEL ubi8 (user image) has 3.9 so those are what we use. I plan to upgrade Focal to Jammy and that will bump python up to 3.10. But upgrading ubi8 to ubi9 is problematic at this point since ubi9 apparently requires z14 and above.
> 
> Keep in sync with other related projects such as onnx and/or llvm is desirable but ultimately it comes down to each project's own requirements.

Understood! Thanks for the valuable feedback and we can close this issue for now and when the time comes upgrade when need be.

**Comment by hamptonm1** [comment]
I am going to close this out for now and when we need to revisit this topic....we can open it up then :)
