### ISSUE TITLE
Improvements to omTensorListCreateWithOwnership

### ISSUE THREAD

**Issue by hamptonm1** [onnx/onnx-mlir#2008]
Based on the documentation updates found in this PR: https://github.com/onnx/onnx-mlir/pull/1922#issuecomment-1371748022

It ignited a broader conversation of potentially updating/improving the current implementation of the `omTensorListCreateWithOwnership` API. 

Here is @AlexandreEichenberger opinion: 
```

This interface is terrible. It may have been designed for unique ptrs and/or for the compiler; for users it is very confusing.

List ownership is only for a very small data... namely a couple of pointers. In my opinion, the pointers should always be copied into a list owned by the list, so that it does not matter when the user's list is freed or not.
I find that forcing to free each tensor of the list is also bad. For example, we may reuse an input tensor in 2 lists, or reused in the same list. Not having the option of manually free the tensor is super bad in my opinion.
If I were to redesign this interface, I would "append" a list past the data structure of the OMTensorList so that no extra malloc is needed, the list is always copied, and "owning" would refer to the tensor themselves... meaning we call the individual tensor destroy for tensors in the list only in presence of the owning field.
```

**Comment by hamptonm1** [comment]
I wanted to use this issue to start a conversation about potential design enhancements we should include for this interface. If we do receive a lot of feedback on this topic then it would be best to have a meeting to deliberate. 

@gongsu832 I know you are super familiar in this area and was requesting your opinion on the matter

**Comment by gongsu832** [comment]
The owning flag was originally designed for OMTensor to avoid having to copy the tensor data which can be large. I don't know when the owning flag was also applied to OMTensorList. I agree that it doesn't make much sense to use the owning flag for OMTensorList since it's typically very small. I would just always internally malloc, copy, and free the list and get rid of the owning flag. Freeing OMTensorList should just free the list, not the tensors pointed to by the list, to allow tensor reuse. Basically, OMTensorList and OMTensor should be managed separately.

**Comment by cjvolzka** [comment]
I'd be fine with dropping ownership entirely from OMTensorList. However we'll want to make sure the rest of the community is on board and aware. That'll be a notable change from the current default behavior so it'll be memleak city for C/C++ applications until they update to match. This is something we should bring up at the next community interlock meeting.

I'm thinkinig in many cases, most people will just want to clean up the whole list so I'd like to keep some way to make that easy. Because client applications will have to update their code for this change no matter what, should we change `void omTensorListDestroy(OMTensorList *list)` to something like `void omTensorListDestroy(OMTensorList *list, bool destroy_tensors)`? Then at List destruction, they have to state what they want instead of us trying to guess.

Some knock on benfits of changing the existing API:
1. No one should have "accidental" because of the change leaks. Since the old `omTensorListDestroy(list)` won't exist, applications won't compile until they update and explicitly decide what to do
1. It will let us remove the "hidden" `omTensorListDestroyShallow()` method.

My big question, is how would the other languages handle this (Java and Python)? Right now you clean up the OMTensorList and all the OMTensors go with it. So will those applications also have to be updated to do an extra cleanup step? Otherwise does the JNI/pybind wrappers have some logic/magic that would automatically handle this for us based on something like reference counting?

**Comment by cjvolzka** [comment]
Overall I want to drop the owning flag from OMTensorList. I think it just adds a bunch of confusion. _If_ we did keep it, then it should control whether or not it frees the OMTensor objects "inside" the OMTensorList. That way it would be conceptually consistent with what "owning" means inside of an OMTensor itself (ie "ownership" means that when the top level object is free'd, it also frees what it "contains").

I like the second option better (removing "owning" entirely from OMTensorList). As you mentioned there's good cases where users want to clean up everything and others where they just want to clean the List but keep some or all of the Tensors.

@gongsu832 is there a reason to not modify omTensorListDestroy() to require callers to explicitly state if they want to clean up all tensors or none? That way in the case they want everything cleaned, it'll still be a single easy call to `omTensorListDestroy(list, true)` rather than:
```
    for (int64_t idx = 0; idx < omTensorListGetSize(list); idx++) {
        omTensorDestroy(omTensorListGetOmtByIndex(list, idx));
    }
    omTensorListDestroy(list);
```

If they wanted to be selective, then they could use such a loop (skipping the Tensors they want to keep) followed by `omTensorListDestroy(list, false)`

This way onnx-mlir never has to "guess" which the user wants but the common case remains easy.

**Comment by gongsu832** [comment]
The argument against adding an argument to `omTensorListDestroy` or any function in general is that giving users more flexibility typically comes with the cost of being more error prone, i.e., users may pass in the wrong flag (due to for example copying and pasting code).

Having said that, in this particular case, I think removing the owning flag and adding the argument so that `omTensorListDestroy` can behave consistently while maintaining the flexibility of controlling whether to free the associated tensors is a reasonable solution.

**Comment by AlexandreEichenberger** [comment]
In light of the discussion above, I agree that removing the `ownership` flag from `omTensorListDestroy` would simplify the interface, and I would that call NOT destroy the tensors in the list.

I would then have another new call `omTensorAndTensorListDestory` (or `omRecursiveTensorListDestory`) destroy every element tensors in the list, and then destroy the list itself.

Note that if we change behavior, we may have to look into the code generated by the compiler.

**Comment by cjvolzka** [comment]
If we give it a new call, I like `omRecursiveTensorListDestory`. 

However my thought on changing the existing `omTensorListDestroy` signature to require a new param means existing applications will _have_ to update their List frees as the old call will be a syntax error. This means someone who pulls in this new onnx-mlir version to rebuild their models, can't miss the change. If we let the original call "as is" but change it's meaning (no longer free Tensors), I'm betting someone doesn't ready the changelog. Then they suddenly has massive memory leaks when the Tensors are no longer cleaned up with the List. 

Although if we wanted to, we could leave the original call `omTensorListDestroy(list)` cleaning up the Tensors. Then add a new `omTensorListDestroyLeaveTensors(list)` (name TBD) call instead. That would also alleviate my concern about preventing unexpected memory leaks from existing applications.

**Comment by gongsu832** [comment]
> Then add a new `omTensorListDestroyLeaveTensors(list)` (name TBD) call instead.

That's basically the currently unexposed `omTensorListDestroyShallow`.

**Comment by hamptonm1** [comment]
Since this current conversation was addressed in Tuesday's meeting.... I will close this issue and open a new one to implement the changes. Thanks!
