### ISSUE TITLE
IndexExpr and Shape Dialect

### ISSUE THREAD

**Issue by weimingzha0** [onnx/onnx-mlir#2029]
Hi,

(This is not an issue, just try to find an answer)

onnx-mlir uses IndexExpr for shape inference. 
Is that because shape dialect is insufficient to express some constraints or expressions?

Thanks

**Comment by AlexandreEichenberger** [comment]
I have had discussions with the shape dialect folks, and we are both after something similar. The issue we both face is that we want to have a single piece of code that can answer questions about shape before code gen (shape inference) as well as during code gen (generate code to compute at execution the dynamic shapes). Shape dialect is a dialect that let you compute shapes, more like the code gen part. 

IndexExpr allow us to express in one go the computations needed to both infer constant shapes (and -1/dynamic) during the shape inference, and use the very same code to generate expressions for dynamic code during code gen.

**Comment by AlexandreEichenberger** [comment]
See how the same ONNXxxxOpShapeHelper are used during shape inference and lowering code.

**Comment by weimingzha0** [comment]
Thanks for the explanation.
Below is my understand:
Shape Dialect can be used to generate code that executes at runtime to compute shape. (I see MLIR emits functions for shape computation).
The reason onnx-mlir uses IndexExpr is because it is easier to use for compile-time shape deduction and propagation.

Is that correct?

**Comment by AlexandreEichenberger** [comment]
> The reason onnx-mlir uses IndexExpr is because it is easier to use for compile-time shape deduction and propagation.

Not quite. ONNX has 100+ ops (like TF, Torch) and we want to have a unique piece of code to compute shape. We use that same code to either generate compile time constants and dynamic values (no code gen, that is the analysis) or generate the ops to compute the dynamic shapes.

Right now, when we generate ops, we introduce arithmetic ops. It would be easy to switch some of it to shape dialects, if needed. We have not had this need internally, probably because our effort started before shape dialect matured. But it could be done relatively easily.

IndexExpr are possibly slightly more encompassing than shape dialect. We have multiple cases where conditional (select) are needed for shapes, so IndexExpr also represents boolean values. (Unfortunately), ONNX also has a few places where floating points operations are needed to compute shapes. We handle these cases in IndexExpr as well.

Aside of all this, code writers in ONNX-MLIR are strongly encouraged to use the existing infra to compute shape. The last thing we want is to have redundant code that recompute shapes in a different way. Standard evolve fast enough that we also want to maintain only one change if shape where to change (it does often between opset releases).

Hope this helps.

**Comment by weimingzha0** [comment]
Great! Thanks. 
This totally makes sense.
