### ISSUE TITLE
Constant Parser/Print

### ISSUE THREAD

**Issue by chentong319** [onnx/onnx-mlir#2044]
When I import a model with `onnx-mlir --EmitONNXBasic` and then read in the .mlir file again with `onnx-mlir --EmitONNXIR`, the attribute for Constant is not DisposableElementAttr and therefore `disposable.printAsDenseElementsAttr(printer)` branch is not taken. Is this expected?
@sorenlassen Is there a way to turn that attribute into disposableElementsAttr or DenseElementsAttr?

**Comment by sorenlassen** [comment]
DisposableElementsAttr is implemented so that it kicks in when the compiler input is .onnx and is imported with FrontendDialectTransformer, which is the expected use case for large real-world models that benefit the most from the memory and speed savings, especially onnx models that use external-data so the large constants are mmap'ed and need not be loaded into RAM.

By design, when we print out .mlir the DisposableElementsAttr are printed as DenseElementsAttr and when you use the .mlir as input again then the attribute will become a DenseElementsAttr. I don't know if it's useful in practice to parse DisposableElementsAttr from .mlir files.

Regardless, if the DenseElementsAttr is an input to a constant propagation or constant folding operation (implemented with the ElementsAttrBuilder methods) then in many cases a DisposableElementsAttr is constructed, exploiting DisposableElementsAttr's ability to avoid memory duplication etc.

Did this answer your question? Please let me know if I misunderstood.

**Comment by chentong319** [comment]
@sorenlassen DisposableElementsAttr is definitely useful for compiler performance. My problem is to use onnx-mlir as a tool to manipulate a model through the .mlir file. For certain purpose, I'd like to print out the Constant value in readable format, even if it is a large f32 tensor. 
By looking into the MLIR code, I think my problem is related to static bool [shouldPrintElementsAttrWithHex](https://mlir.llvm.org/doxygen/AsmPrinter_8cpp.html#a2feda6688b0fb978ee8848de2a4ea8b2)(int64_t numElements), not related to disposableElementAttr. We always print out disposableElementAttr as DenseElementsAttr. Is that true?

**Comment by sorenlassen** [comment]
> We always print out disposableElementAttr as DenseElementsAttr. Is that true?

yes, with the exception of the examples listed in issue #1975 (which might all be error cases due to verifier failures)

**Comment by chentong319** [comment]
The flag `--mlir-print-elementsattrs-with-hex-if-larger -1` solved my problem.
