### ISSUE TITLE
function call shape inference

### ISSUE THREAD

**Issue by sorenlassen** [onnx/onnx-mlir#2185]
As discussed in PR #2175 shape inference doesn't work for function calls: ONNXCallOp doesn't implement ShapeInferenceOpInterface and if we modify a function's return shapes during shape inference then we'll break all call ops to that function. Given that this doesn't work, ShapeInferencePass (and ONNXHybridTransformPass which also does shape inference) is currently a function pass even if it modifies function signatures, which is probably improper behavior of a function pass but doesn't matter since a function's signature is not currently used outside the function in any meaningful way.

If we want to implement function calls properly, we'll need to come up with a strategy for shape inference to propagate updates to return shapes to callers, maybe with some kind of module-level fixpoint iteration.

As mentioned in issue #1787 there are a number of other problems with the implementation of function calls in the ONNX dialect. One solution is to inline function calls during onnx import. Any solution we choose should ideally support model-local functions, see issue #1841.

cc @chentong319

**Comment by chentong319** [comment]
First, I need some clarification on ONNXCallOp and functions for a model. I never handled a model using ONNXCallOp.
By reading the [onnx document](https://onnx.ai/onnx/api/classes.html#functionproto) and our builder code (FrontendDialectTransformer.cpp:TryImportFunctionCallNode), I feel the key question is whether a function body is called only by a ONNXCallOp. This means a function body has only one calling context. It will simplify our work a lot. The first approach occurred to me is to use MLIR inlining function method to eliminate ONNXCallOp and functions, leaving only the top functions.

If the functions may be called from different ONNXCallOps, it will be a different story. We have to propagate shape info in the call graph/tree in both directions.

**Comment by sorenlassen** [comment]
I believe FrontendDialectTransformer.cpp:TryImportFunctionCallNode only creates one caller for each function, which is why I suggested in issue #1787 that we just inline in FrontendDialectTransformer and get rid of ONNXCallOp (proof of concept implementation in PR #1785), ONNXCallOp doesn't have implementation of shape inference or lowering so it's not useful currently

but if we want to support model-local functions (issue #1841) then maybe it's worthwhile having real functions and function calls, and then we'd need to figure out shape inference (and lowering)

**Comment by chentong319** [comment]
Should we go ahead with PR#1785 for schema-based function first? 
I deleted my previous comment by mistake.

**Comment by chentong319** [comment]
About lowering ONNXCallOp:
I implemented KrnlCallOp to lower a ONNX Op to a library call. ONNXCallOp and KrnlCallOp is similar. The major difference is that KrnlCallOp takes in function name as string, instead of FlatSymbolAttr,  output MemRefs and inputs of any type (for Memref and attributes from an Op).  KrnlCallOp is then lowered to llvm. Some code may be reused. 
ONNXCallOp does not have attribute input for function, not like converting an ONNX Op to a call. This is obvious. The explanation of the other two difference may help us understand the issues with ONNXCallOp.

**Take output MemRef as an parameter**
Shape inference analysis for each ONNX Op creates a shape transfer function. The output of the function is the size of each dimension of the output, while the inputs are 1) the dimension of inputs 2)  the size of each dimension of input, 3) the value of attributes, and 4) the value of the input parameters. Quasi-affine functions (perhaps more relaxed now) are used. In this way, we can allocate MemRef for tensor with dynamic dimensions.  krnlCallOp does not have the shape transfer function. Therefore, when an ONNX Op is translated to krnlCallOp, the result memref should be created and passed to krnlCallOp.
Now ONNXCallOp does not have this problem. The output memref (after lowering) will be created inside the function. There may be some bufferization interface details involved. For example, a tensor is passed into the function and then returned from the function. 

**Function signature**   
If the tensor type is used for function signature, it will become weird that the signature may be changed by shape inference. At lower level, the interface for MemRefs are the same. To me, the signature of FunctionProto provides the basic shape inference (in sense of onnx), which is just element type inference, in most cases, in onnx-mlir. It might be a problem to map that signature directly to MLIR function signature. So KrnlCallOp creates the FlatSymbol for function only at LLVM level.




The key issue for shape inference and lowering related 
For the function signature

**Comment by chentong319** [comment]
If we have a function, can we perform a quick shape inference for a caller?
Remember my previous comments on the shape transfer function onnx-mlir defined for each ONNX Ops. For a sequence of Ops, their shape transfer function can be composed into one transfer function if value computed in the function is NOT used in transfer function for individual Op. 
If this is true for a function, we can compute the output shape quickly. The composition of transfer function might be what inferShape of ONNXCallOp should be.

**Comment by chentong319** [comment]
Agree on the assumption that the call graph is acyclic.

Inlining or not is the key decision to us. If all function calls are inlined, no further issue for compiler. Should I review PR#1785 as our first step to go ahead? 

Or should we focus on what to do if function call is not inlined for certain reasons? The model size could be a reason. Another reason could be for library call.

**Comment by chentong319** [comment]
Agree on
1. Use ONNXFunctionReturnOp to preserve the function signature.
2. Cloning may help in reducing the code size, compared with inlining. It is a good idea. 

Some details
What function signature can be expected? An ONNX Op is quite general and can take tensors with different dimension, different dimension size and element type. Though the ONNX function is designed to represent customized Op, function will have some limitations. Element type has to be specified due to the support of MLIR.  How about number of dimension? If unranked tensor is used for signature, we can not do much shape inference from the function signature, but have to collect calling context for shape inference.
For the cloning infrastructure, if we define the hybrid transformation on function, can we generated new functions in the process of transformation? When an ONNXCallOp is encountered, we need to clone the function to get new function, if needed. Then we can add a dynamic pipeline on that function to get the returned type. Is that in your mind?

**Comment by sorenlassen** [comment]
> What function signature can be expected? An ONNX Op is quite general and can take tensors with different dimension, different dimension size and element type. Though the ONNX function is designed to represent customized Op, function will have some limitations. Element type has to be specified due to the support of MLIR. How about number of dimension? If unranked tensor is used for signature, we can not do much shape inference from the function signature, but have to collect calling context for shape inference.

I think the primary use case is tensor inputs and I guess they may be unranked and then we will rely on cloning the function to ranked input types (ideally static shapes) for shape inference

> For the cloning infrastructure, if we define the hybrid transformation on function, can we generated new functions in the process of transformation? When an ONNXCallOp is encountered, we need to clone the function to get new function, if needed. Then we can add a dynamic pipeline on that function to get the returned type. Is that in your mind?

I think it might be enough if the shape inference pass does the cloning: that seems to be in line with how we frequently call shape inference between transformation passes to propagate shapes

**Comment by sorenlassen** [comment]
> Inlining or not is the key decision to us. If all function calls are inlined, no further issue for compiler. Should I review PR#1785 as our first step to go ahead?

In the long term I think we agree that we would like to make ONNXCallOp work and we will not want to always inline everything in FrontendDialectTransformer, because there may be future uses where a function is called multiple times and we not inlining would lead to smaller model size, as you mentioned. However, if we agree to only support acyclic call graphs then inlining in FrontendDialectTransformer works and is the fastest way to get things working, so I'll try to make a new version of PR #1785 that doesn't remove ONNXCallOp and where you can control inlining with a flag.

**Comment by AlexandreEichenberger** [comment]
Read through the comments here, not sure I understand all of the points. If I understand well, we are excluding cycles in call graphs (reasonable, can be tested). 

1. So we can order functions, starting at the root one... when encountering a call, we can use the shape we have up to now for that function, and analyze its body. Eventually (if there are nested functions, visiting other functions with the same mechanism) we will return to the original call.
2. Now that was a lot of work, and we need to find a fix point anyway, so we don't want to repeat this over and over again.
3. I heard the idea of cloning... and that is good because eventually, if there are 3 types of call size (say one with input 128x128, one with 256x256, and one with 1024x1024), it would be great to clone each type so that we can run it with constant sizes... But maybe cloning for the purpose of analysis is a bit extreme. So what about:
4. We record the signature of the inputs and outputs in strings (we already have a json reader for that) or some other format and attach it to the call operation as an attribute. If we come back to this same function, and see that the shape of the inputs are the same as the recorded input signature. We have fix point, and we don't need to recompute the output shape. If the inputs are more specific, then we can re-shape-infer this call site to refine the output shape associated with this call graph.
5. Since we don't want to do more work than needed, we can keep a cache of <function name, inputs> -> <output signature, ref count>... so when we see the same call with the same input, we can simply retrieve the output signature. Ref count can be used to determine which one are good candidate for cloning.

hope this helps.

I still think it might make sense to evaluate the need to keep function un-inlined. If we don't have in specific implementation for it, inlining is good. If we have a specific implementation for it, we should come up with a "custom" shape inference also (note that multiple shape inference objects can also be called by hand for combined operations)

**Comment by chentong319** [comment]
(My comment in PR#1785. Let's put all relevant discussion here)

For inlining, I think that we are going to use the inline support from MLIR, aren't we? The FrontendDialectTransformer.cpp will remain the same, leaving option of inlining or cloning to the later pass. The MLIR tutorial described an inlining example (https://mlir.llvm.org/docs/Tutorials/Toy/Ch-4/#inlining). Should we try that with onnx-mlir?

**Comment by sorenlassen** [comment]
> we need to find a fix point anyway, so we don't want to repeat this over and over again

if the call graph if acyclic then we probably don't need a fix point to infer caller-callee shapes

(but there are some ideas about fix point calculation of shapes for the Loop and Scan ops)

> we can keep a cache of <function name, inputs> -> <output signature, ref count>... so when we see the same call with the same input, we can simply retrieve the output signature. Ref count can be used to determine which one are good candidate for cloning

yes, I think it'll be useful to track all the clones of a given function, e.g. when a caller's operand gets a more specific shape because of a rewrite then we can look up if there's already another clone of the function with that argument shape

the simplest might be to set an attribute on a clone to say what it was cloned from and then construct the mapping for a module when we need to look this up, there will probably never be many functions so the cost of constructing the mapping should be cheap and we generally avoid data structures outside of the IR itself (with DisposablePool being one of the rate exceptions which is maintained as a DialectInterface)

in any case, it's probably only the shape inference pass who should clone functions and it can also garbage collect clones whose callers disappear or migrate to more specific shapes (we generally rely on the shape inference pass to propagate shapes)

**Comment by sorenlassen** [comment]
> Can we have at least one onnx model with function call in git repository?

issue #1841 lists some small test examples onnx models with model-local functions

the other use case for functions is to exploit how some operators are expressed as functions in terms of more primitive operators https://github.com/onnx/onnx/blob/main/docs/AddNewOp.md#step1_new_operator_or_function

in either case we can use the test/mlir/onnx/parse framework to put it in the onnx-mlir repository together with a test of how we import it in FrontendDialectTransformer:
https://github.com/onnx/onnx-mlir/blob/main/test/mlir/onnx/parse/string_data.json
https://github.com/onnx/onnx-mlir/blob/main/utils/testing/string_data.py

**Comment by sorenlassen** [comment]
as discussed in today's onnx-mlir informal meeting, I am closing this issue as "will not fix" and will instead pursue the inlining approach described in issue #1787
