### ISSUE TITLE
docker cannot start

### ISSUE THREAD

**Issue by guojilei** [onnx/onnx-mlir#2500]
Hi 
 I've  pulled the onnxmlirczar/onnx-mlir image, then I created a docker with the following command
 `docker run -itd --name mlir onnxmlirczar/onnx-mlir:amd64 /bin/bash`
but the mlir docker is Exited。I tried to start this docker with docker start mlir, but The status of mlir is still Exited. when i enter docker logs mlir ,  I got fllowing message.
`Invalid input file "/bin/bash": Either an ONNX model (.onnx or .onnxtext or .json), or an MLIR file (.mlir) needs to be provided.`
What can I do to solve this problem?
Thank u

**Comment by gongsu832** [comment]
What are you trying to do, compile a model or develop for onnx-mlir? The `onnxmlirczar/onnx-mlir` image is not meant to be run interactively. It's meant to be a quick way to run onnx-mlir to compile a model without installing anything. See the docs at https://github.com/onnx/onnx-mlir/blob/main/docs/Docker.md

If you insist on running the `onnxmlirczar/onnx-mlir` interactively, you can use
```
docker run -it --name mlir --entrypoint=bash onnxmlirczar/onnx-mlir
```

**Comment by guojilei** [comment]
Thank u for your reply, I want to complie a model. Now I have pulled this image. In my opinions . if i want to achieve my goal . There are  three steps need to do . <1>pull this image <2> create a docker use this image. <3> Enter docker and compile a onnx model. Maybe I have some misunderstanding about the use of image. what i should to compile a model use this   ##image.
Thank u

**Comment by gongsu832** [comment]
The command is in the onnx-mlir source repo. You need to clone the onnx-mlir source repo.

**Comment by guojilei** [comment]
sorry I have another question , 
do you mean it is enough to compile a onnx model when i have this image and onnx-mlir source code.? i need not to compile and build llvm . 
Thank u

**Comment by gongsu832** [comment]
The `onnxmlirczar/onnx-mlir` image alone is enough to compile a model. But since the onnx-mlir compiler is running inside a container, it does not have direct access to a model file on your host. So docker run command options are needed to mount the host directory containing the model file into the container. So if you know how to do that yourself, you can just run the `onnxmlirczar/onnx-mlir` image and supply those options yourself manually. The `docker/onnx_mlir.py` script in the source repo is just a convenience script that takes care of those details for you.
