### ISSUE TITLE
Dynamic backend tests on NNPA cause errors

### ISSUE THREAD

**Issue by negiyas** [onnx/onnx-mlir#2817]
Dynamic backend tests on NNPA cause runtime errors. (c.f. This Issue is similar to Issue #2743 "Dynamic backend tests cause errors on CPU," but this issue for errors on NNPA.)

PR #2781 introduces "--dimParams" option for specifying relationships among dimensions of model inputs. It also enables dynamic backend tests on NNPA with the --dimParams option, but some tests cannot be enabled because of runtime errors, and they are temporally disabled by the PR. We need to fix these runtime issues or confirm that they are reasonable.

The following is a list of backend tests on NNPA not causing errors with static shapes, but causing errors with dynamic shapes. Please fix errors or confirm that they are reasonable. Thanks.

[ ] test_averagepool_2d_default_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_averagepool_2d_precomputed_pads_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_averagepool_2d_precomputed_same_upper_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_averagepool_2d_precomputed_strides_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_averagepool_2d_same_upper_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_averagepool_2d_strides_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_batchnorm_epsilon_cpu,zdnn_mul,NO_DYNAMIC_SHAPE_TEST
[ ] test_batchnorm_example_cpu,zdnn_mul,NO_DYNAMIC_SHAPE_TEST
[ ] test_basic_conv_with_padding_cpu,zdnn_conv2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_basic_conv_without_padding_cpu,zdnn_conv2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_conv_with_strides_no_padding_cpu,zdnn_conv2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_conv_with_strides_padding_cpu,zdnn_conv2d,NO_DYNAMIC_SHAPE　_TEST
[ ] test_globalaveragepool_cpu,zdnn_meanreduce2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_globalaveragepool_precomputed_cpu,zdnn_meanreduce2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_logsoftmax_example_1_cpu,zdnn_softmax,NO_DYNAMIC_SHAPE_TEST
[ ] test_max_float32_cpu,zdnn_max,NO_DYNAMIC_SHAPE_TEST
[ ] test_maxpool_2d_default_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_maxpool_2d_precomputed_same_upper_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_maxpool_2d_precomputed_strides_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_maxpool_2d_same_upper_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_maxpool_2d_strides_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_min_float32_cpu,zdnn_min,NO_DYNAMIC_SHAPE_TEST

**Comment by imaihal** [comment]
I found that most test cases for avgpool run on CPU because we don't know they meet one of the parameter restriction `Input tensor batch_Num and Channel dimensions must always match the output tensor's respective dimensions.` in [AvgPool2D Parameter Restrictions ](https://github.com/IBM/zDNN?tab=readme-ov-file#avgpool2d-parm-restrictions ) when input is unknown dimension.

Since we can't check it at compile time, I think we can ignore it in unknown dimension case. (If this doesn't meet at runtime, the execution fails at runtime. ) By fixing the legality check, I confirmed most of the case can run on NNPA.

`test_averagepool_2d_precomputed_pads_cpu` really can't be run on NNPA because padding type is not calculated in unknown dimension.  

[ ] test_averagepool_2d_default_cpu,zdnn_avgpool2d, ~~NO_DYNAMIC_SHAPE_TEST~~
[ ] test_averagepool_2d_precomputed_pads_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST # Padding type is not `SAME_PADDING` or `VALID_PADDING`
[ ] test_averagepool_2d_precomputed_same_upper_cpu,zdnn_avgpool2d,~~NO_DYNAMIC_SHAPE_TEST~~
[ ] test_averagepool_2d_precomputed_strides_cpu,zdnn_avgpool2d,~~NO_DYNAMIC_SHAPE_TEST~~
[ ] test_averagepool_2d_same_upper_cpu,zdnn_avgpool2d,~~NO_DYNAMIC_SHAPE_TEST~~
[ ] test_averagepool_2d_strides_cpu,zdnn_avgpool2d,~~NO_DYNAMIC_SHAPE_TEST~~

**Comment by imaihal** [comment]
Now only test cases with `[x]`  (8 cases) do not support dynamic tests by PR #2831 . The remaining tests with `[ ]` support dynamic tests. So, `NO_DYNAMIC_SHAPE_TEST` was removed from them.

[ ] test_averagepool_2d_default_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[x] test_averagepool_2d_precomputed_pads_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_averagepool_2d_precomputed_same_upper_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_averagepool_2d_precomputed_strides_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_averagepool_2d_same_upper_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_averagepool_2d_strides_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_batchnorm_epsilon_cpu,zdnn_mul,NO_DYNAMIC_SHAPE_TEST
[ ] test_batchnorm_example_cpu,zdnn_mul,NO_DYNAMIC_SHAPE_TEST
[x] test_basic_conv_with_padding_cpu,zdnn_conv2d,NO_DYNAMIC_SHAPE_TEST
[x] test_basic_conv_without_padding_cpu,zdnn_conv2d,NO_DYNAMIC_SHAPE_TEST
[x] test_conv_with_strides_no_padding_cpu,zdnn_conv2d,NO_DYNAMIC_SHAPE_TEST
[x] test_conv_with_strides_padding_cpu,zdnn_conv2d,NO_DYNAMIC_SHAPE　_TEST
[x] test_globalaveragepool_cpu,zdnn_meanreduce2d,NO_DYNAMIC_SHAPE_TEST
[x] test_globalaveragepool_precomputed_cpu,zdnn_meanreduce2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_logsoftmax_example_1_cpu,zdnn_softmax,NO_DYNAMIC_SHAPE_TEST
[ ] test_max_float32_cpu,zdnn_max,NO_DYNAMIC_SHAPE_TEST
[ ] test_maxpool_2d_default_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[x] test_maxpool_2d_precomputed_pads_cpu,zdnn_maxpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_maxpool_2d_precomputed_same_upper_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_maxpool_2d_precomputed_strides_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_maxpool_2d_same_upper_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_maxpool_2d_strides_cpu,zdnn_avgpool2d,NO_DYNAMIC_SHAPE_TEST
[ ] test_min_float32_cpu,zdnn_min,NO_DYNAMIC_SHAPE_TEST

**Comment by negiyas** [comment]
Closing this issue, since all tests were fixed or confirmed. Thanks.
