### ISSUE TITLE
The name of ONNF is misleading

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx-mlir#4]
ONNF is indicating that ONNX is another ML frontend (like tf, pytorch, etc), which is not true and adding chaos when promoting it to be a shared (common) mlir dialect later (which I think is the one of the goals of this work).

How about naming it as "ONNX dialect" directly? @tjingrant

**Comment by tjingrant** [comment]
If we go with the onnx-mlir branding, will it resolve your concern? It'd be a bit simpler.

**Comment by caoimhinuibrian** [comment]
I agree. We should just drop the ONNF name, it’s not actually adding anything.

Kevin

**Comment by tjingrant** [comment]
Sounds good, will switch to onnx-mlir throughout our codebase. 
@linkerzhang please let me know your thought!

**Comment by linkerzhang** [comment]
Thanks! onnx-mlir is better than onnf :), though I'll be open to other even more descriptive names if any (I'm not good at naming at all, btw.).

**Comment by bhack** [comment]
As the ONNX dialect is a quite different third party dialects cause It is related to a standard do you plan to contribute It in https://github.com/llvm/llvm-project/tree/master/mlir/lib/Dialect?

**Comment by bhack** [comment]
There is just a new doc if you are interested https://github.com/llvm/llvm-project/blob/master/mlir/docs/CreatingADialect.md

**Comment by tjingrant** [comment]
It is one of our goals to try and see if there is a place for ONNX to exist within MLIR core. But it seems like we have some distance to cover and more work/discussions are needed before we can tell whether MLIR core is the right place for ONNX dialect and whether the MLIR community is willing to accept the ONNX dialect - c.f. https://groups.google.com/a/tensorflow.org/forum/#!msg/mlir/CUL3_8fnJb4/0Uvt3M-FAQAJ.

**Comment by bhack** [comment]
Yes but the MLIR community position was a little bit evolved from the google group post.
I.e. See https://llvm.discourse.group/t/development-of-high-level-tensor-compute-primitives-dialect-s-and-transformations/388/57

**Comment by AlexandreEichenberger** [comment]
Thanks, nice to hear that they are softening on the usefulness of the ONNX dialect. I concur with Tian that it would be best for us to continue developing the dialect separately for a little while so that we may come with a comprehensive approach.
Alexandre-----------------------------------------------------------------------------------------------------Alexandre Eichenberger, Principal RSM, Advanced Compiler Technologies- research: compiler optimization (OpenMP, GPU, SIMD)- info: alexe@us.ibm.com http://www.research.ibm.com/people/a/alexe- phone: 914-945-1812 (work), 914-312-3618 (cell)
 
 
----- Original message -----From: bhack <notifications@github.com>To: onnx/onnx-mlir <onnx-mlir@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [EXTERNAL] Re: [onnx/onnx-mlir] The name of ONNF is misleading (#4)Date: Sat, Mar 7, 2020 10:50 AM 
Yes but the MLIR community position was a little bit evolved from the google group post.I.e. See https://llvm.discourse.group/t/development-of-high-level-tensor-compute-primitives-dialect-s-and-transformations/388/57

**Comment by bhack** [comment]
Ok but try to early interact with them on discuss/Discord.

**Comment by doru1004** [comment]
Fixed by https://github.com/onnx/onnx-mlir/pull/32
