### ISSUE TITLE
Release builds not working without assertions

### ISSUE THREAD

**Issue by NathanielMcVicar** [onnx/onnx-mlir#420]
After #386 it seems that assertions are required for correct operation due to MatMul.cpp:28. However, they are disabled for Release builds in the top level CMakeList.txt. We are observing this problem in our local pipelines, but this doesn't appear to be an issue for CI, so I'm wondering if some additional step should be reenabling assertions. We're following the docs for our build, as far as I can tell. Thanks!

**Comment by tjingrant** [comment]
Maybe try removing `NDEBUG` flag in this line?

https://github.com/onnx/onnx-mlir/blob/0211de8a7ae352bda09838c19b401b83a9398bf5/CMakeLists.txt#L11

**Comment by NathanielMcVicar** [comment]
We tried this, but it didn't work for our build system. Regardless, it seems more correct not to wrap functional code in assertions? If you prefer I remove the change I will investigate further.

**Comment by tjingrant** [comment]
> Regardless, it seems more correct not to wrap functional code in assertions?

I agree. 

>  If you prefer I remove the change I will investigate further.

If by "the change" you mean pulling functional code out of assertion, I'm fully on board with it. OTOH, I suspect Cmake is nevertheless inserting the `NDEBUG` macro definition when building in release mode even if we don't specify it explicitly. I think whether enabling assertions in release-mode is the right thing to do is up for debate, and having an easy way (i.e., `RelWithDebInfo`) around this issue seems to be a good enough solution for most people.

I guess my question would be, does the changes introduced in your PR draft address the issues you're encountering? And if not, whether there're things you'd expect from my (or other collaborators') end which can help you move forward?

**Comment by NathanielMcVicar** [comment]
> I guess my question would be, does the changes introduced in your PR draft address the issues you're encountering? And if not, whether there're things you'd expect from my (or other collaborators') end which can help you move forward?

Yes, pulling the code out, as in this PR, fixes the release build in our environment. In terms of why assertions aren't working in our Release build, despite working in you all's CI, I do plan on looking into it more at some point, but it's not a high priority after this change. As you say, we can use RelWithDebInfo if we need to.

**Comment by tjingrant** [comment]
> In terms of why assertions aren't working in our Release build, despite working in you all's CI, I do plan on looking into it more at some point,

We don't build in Release mode on our CI though. Windows build is an exception I guess, because the Windows-CI only tests whether onnx-mlir builds, no tests are run.
