### ISSUE TITLE
Reuse weight parameter

### ISSUE THREAD

**Issue by feiyuvl** [onnx/onnx-mlir#560]
According to the `test/numerical/TestConv.cpp`,  we need to copy weight each time we call the convolution function. Is there any method to set weight once, and avoid copying each time when computing?

**Comment by caoimhinuibrian** [comment]
Not sure what you're asking. This is a testcase checking numerical accuracy.

**Comment by feiyuvl** [comment]
When we do inference for a nerual network, for example resnet, we only init weight once, then with different input data. Does onnx-mlir support global variable to store weight parameter?

**Comment by caoimhinuibrian** [comment]
Yes, the weights are stored in a global constant pool

**Comment by feiyuvl** [comment]
Thank you. Is there any example?

**Comment by caoimhinuibrian** [comment]
Not sure what you want to see. Take any trained model, use onnx-mlir to compile it, link it with a driver and run it multiple times with inputs. The weights are saved in the model binary. You do not need to specify them in order to run the inference. For an example use mnist or resnet or something else that is available out there.
