### ISSUE TITLE
Question about the OMTensor.h interface

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#645]
First, I think we should add the signature for the call:

```
extern "C" OMTensorList *run_main_graph(OMTensorList *);
```

I failed to add it and I was getting loader symbol not found, because it was in a cpp file. Is there any reason not to add it?

Second, I find the interface to `OMTensorListCreate` counter intuitive because unlike the "shape" parameter (which is copied when creating a tensor), this list is not copied.  However it is deallocated if the owning is set. I understand it is documented, but I still find it counter intuitive.

Note also that if you wanted to optimize the number of alloc, one could also size up the data structures (e.g. assuming  tensors rarely have more than rank 10, one could size up the data structure "OMTensor" with 2x10 ints and point the pointers to that internal pre-reserved arrays. And only when more than 10, then use a malloc. Same trick can be done for omTensorList, as probably models rarely have more than 10 inputs...

**Comment by tjingrant** [comment]
> I failed to add it and I was getting loader symbol not found, because it was in a cpp file. Is there any reason not to add it?

I think there's good reason to both both sides of the arguments (include it or leave it out). Including it, as you experienced, it a lot easier for most users. However, I think convenience only applies when you're working with a single model. If users would like to link with multiple models, (and assuming that we provide ways to name the entry point function differently for different models), it'd be much more natural to ask users to declare those entry point functions themselves. But again, the latter case might be rare, and therefore doesn't really warrant our consideration too much.

> Second, I find the interface to OMTensorListCreate counter intuitive because unlike the "shape" parameter (which is copied when creating a tensor), this list is not copied. However it is deallocated if the owning is set. I understand it is documented, but I still find it counter intuitive.

I think the underlying guiding principles of the current implementation are that:
- Copying is preferred because it separates concerns by effectively preventing unexpected side effects to creep in from callee to caller and vice versa. Also not copying means articulating memory management policies, meaning more docs for us to write and more for users to read.
- Small primitive data type arrays are cheap to manipulate (copy), and struct data types are perhaps less so. I think copying a list of tensors might be fine but may raise some eyebrows.
- Perhaps specific to this case, if we're not careful and we make copies of tensors that own the underlying data, we will end up with two or more tensors each claiming to own the underlying memory buffer, causing the underlying memory buffers to be freed twice or more.

> Note also that if you wanted to optimize the number of alloc, one could also size up the data structures (e.g. assuming tensors rarely have more than rank 10, one could size up the data structure "OMTensor" with 2x10 ints and point the pointers to that internal pre-reserved arrays. And only when more than 10, then use a malloc. Same trick can be done for omTensorList, as probably models rarely have more than 10 inputs...

This makes sense, let's add these optimizations to our wishlists.

**Comment by AlexandreEichenberger** [comment]
@tjingrant Thanks for the reply. 

> I think there's good reason to both both sides of the arguments

make sense. I see that there is a good example in the OnnxMlirRuntime.h, I should have looked at it more closely when starting to code. The example does not seems to free the data structures, maybe I can add that.

> I think there's good reason to both both sides of the arguments

I agree for the data, but not for the list. It's like "size" or "offset"... small and simpler to belong to the data-structure. From how I read the code, the "owning" still only apply to the tensor list, not the tensor themselves. So the user still need to go and free each tensor themselves,  right?
