### ISSUE TITLE
Fail to build on window (sys/time.h missing file)

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#774]
@chentong319 I have not followed closely the additions to the instrumentations, but it is possible that the Window failure that I saw in one of my PRs is due to a change of yours. Its probably a very small change/

@NathanielMcVicar @sstamenova Maybe you would know what the equivalent of "sys/time.h" is on Window? Tx

Thanks for looking into it.

```
ShapeInferenceOpInterface.cpp
  Building Custom Rule D:/a/1/onnx-mlir/src/Interface/CMakeLists.txt
  OMInstrument.c
  OMTensor.c
D:\a\1\onnx-mlir\src\Runtime\OMInstrument.inc(39,10): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory (compiling source file D:\a\1\onnx-mlir\src\Runtime\OMInstrument.c) [D:\a\1\onnx-mlir\build\src\Runtime\cruntime.vcxproj]
  OMTensorList.c
  OnnxDataType.c
  onnx_proto.vcxproj -> D:\a\1\onnx-mlir\build\Release\lib\onnx_proto.lib
  Building Custom Rule D:/a/1/onnx-mlir/src/Dialect/ONNX/CMakeLists.txt
  Building Custom Rule D:/a/1/onnx-mlir/src/Runtime/jni/CMakeLists.txt
  OMShapeInferenceOpInterface.vcxproj -> D:\a\1\onnx-mlir\build\Release\lib\OMShapeInferenceOpInterface.lib
  jniwrapper.c
  jnilog.c
```

**Comment by AlexandreEichenberger** [comment]
I see that there are implementation of gettimeofday out there for window.

https://stackoverflow.com/questions/10905892/equivalent-of-gettimeday-for-windows

**Comment by sstamenova** [comment]
@chentong319  @AlexandreEichenberger: It looks like https://github.com/onnx/onnx-mlir/pull/750 is the change that introduced the failure in the Windows CI. Did the Windows CI not fail for the change itself? It really should have, so that the failure shouldn't have been checked in. If it didn't, we should figure out why.

Regardless, this is a good summary of the various options for time functionality available on Windows: https://docs.microsoft.com/en-us/windows/win32/sysinfo/about-time

I can have a look at fixing the break on Windows later this week, but if @chentong319 can have a look before that or if we could revert #750 until it can be fixed, that would prevent further breaks on Windows from being checked in.

**Comment by chentong319** [comment]
@sstamenova It is #750. The reason is some os-related utility, such as `gettimeofday` and `system()` and `ps`, are used to get runtime info when the model is executed. It is not the essential part to compile or run a model, and is a prototype. I am thinking to put a `#if` for windows system to provide just an empty function and add the right function later when the code becomes stable. At least, onnx-mlir can be compiled and run without instrumentation functionality on window for now. How do you think?

**Comment by sstamenova** [comment]
> @sstamenova It is #750. The reason is some os-related utility, such as `gettimeofday` and `system()` and `ps`, are used to get runtime info when the model is executed. It is not the essential part to compile or run a model, and is a prototype. I am thinking to put a `#if` for windows system to provide just an empty function and add the right function later when the code becomes stable. At least, onnx-mlir can be compiled and run without instrumentation functionality on window for now. How do you think?

That would work. Please add me to the PR, so I can have a look.

**Comment by caoimhinuibrian** [comment]
@chentong319 @sstamenova Please go ahead with this fix. I've made the Windows CI required going forward
