### ISSUE TITLE
Add ONNX dialect into a standalone project

### ISSUE THREAD

**Issue by xinjin95** [onnx/onnx-mlir#790]
Hi onnx-mlir team and friends,

I am working on a dialect translation project. I'd like to add [onnx dialect](https://github.com/onnx/onnx-mlir/tree/master/src/Dialect/ONNX) into my project. How could I write my cmake file? For mlir and llvm, we can add them into a standalone project by `find_package`. Is there a similar way for onnx dialect adding?

Thanks!

**Comment by AlexandreEichenberger** [comment]
@gongsu832 Can you respond? Think you probably have the best view of this. Tx

**Comment by caoimhinuibrian** [comment]
@sstamenova has been most active with cmake recently, maybe she can answer? I have a feeling we haven't added support for this yet.

**Comment by sstamenova** [comment]
There is no support for `find_package` for the onnx dialect (or the krnl dialect, or anything else) at the moment. I think the easiest solution right now would be to use the build directory of onnx-mlir as a starting point for finding the correct headers and libraries and manually setting up the properties that `find_package` would set up if it was supported.

**Comment by xinjin95** [comment]
Hi @sstamenova, thank you so much for your kind information. 

`find_package` will try to find the Module or Config `.cmake` files. In llvm and mlir, `find_package` can find the Config `.cmake` file under the `llvm-project/build/lib/cmake/` directory. But I was not able to find the corresponding find in onnx-mlir's build directory.

If I want to include `src/Dialect/ONNX` into my project, which headers and libraries in build directory should I use?

**Comment by sstamenova** [comment]
Since onnx-mlir does not have an export/config `.cmake` file, you have two options:

1) Add one and send a pull request for it
2) Add the necessary setup in your project

2) is less good long-term and it might have issues, because I am not sure if all the correct headers get installed or binplaced, but it won't touch onnx-mlir. You could do something like this:

* Add a cmake variable to your project, `ONNX_MLIR_DIR` and point it to the onnx-mlir build or install directory. In either case, you might also have to add `ONNX_MLIR_SRC_DIR` and point it to the onnx-mlir source directory if the correct headers aren't being installed or binplaced.
* Add `ONNX_MLIR_DIR/include' to your include directories (you might have to add `ONNX_MLIR_SRC_DIR/include` to your include directories
* Add `ONNX_MLIR_DIR/lib` to your lib directories
* Link against `OMOnnxOps` - this will require some other onnx-mlir libs as well, you will have to get the list from the cmake files

@caoimhinuibrian @AlexandreEichenberger : have there been other requests for `find_package` functionality for onnx-mlir? It might be worth investing in if there has been interest since I don't think it would be too difficult to add.

**Comment by AlexandreEichenberger** [comment]
@sstamenova Is it something that someone under your org might be willing to do?
@gongsu832 if you see values and have some time?

**Comment by sstamenova** [comment]
@AlexandreEichenberger: Is this still the only request for `find_package` functionality? If so, I don't think we would invest in it since we don't need it.

**Comment by AlexandreEichenberger** [comment]
closing request, will rely on folks needing this feature to implement it
