### ISSUE TITLE
Threat all warnings as errors.

### ISSUE THREAD

**Issue by etiotto** [onnx/onnx-mlir#936]
Given that `onnx-mlir` is a project that leverages LLVM and MLIR, and that the LLVM code policy is to consider warnings as if they were errors (https://llvm.org/docs/CodingStandards.html#treat-compiler-warnings-like-errors), I think we should attempt to keep the code as clean as possible and add options to the `cmake` files to force the build compilers(s) to stop compilation when a warning is detected.

The option we can use are:
  - clang & gcc compilers:  `-Werror`
  - MSVC: `/WX`

![Screen Shot 2021-10-20 at 11 27 30 AM](https://user-images.githubusercontent.com/56368199/138123441-0a8914d8-adba-4484-bac0-c85f4b796a0e.png)

**Comment by sstamenova** [comment]
I would recommend following the `llvm-project` pattern and having a cmake variable that turns this functionality on or off. `LLVM_ENABLE_WERROR` is the llvm variable. 

I have not tested it, but I suspect that because we import `HandleLLVMOptions.cmake` from `llvm-project`, passing `LLVM_ENABLE_WERROR` to the cmake for `onnx-mlir` will work already. If you want an `onnx-mlir` specific variable, you could add `ONNX_MLIR_ENABLE_WERROR` as an option and then use it to set `LLVM_ENABLE_WERROR` and leave all the heavy lifting to `llvm-project`.

**Comment by etiotto** [comment]
Thanks @sstamenova for the useful pointer. I was just looking at that file and I would also prefer to reuse `LLVM_ENABLE_WERROR` is that works. We could initially add the code, and leave `LLVM_ENABLE_WERROR` off by default. Then transition to `LLVM_ENABLE_WERROR` on in steps (or use a similar variable).

**Comment by sstamenova** [comment]
I would avoid adding the logic if `LLVM_ENABLE_WERROR` works. I suggest trying it locally and see if passing the variable to cmake has the desired effect. Then all you have to add to the cmake for onnx-mlir will be something like:

`option(ONNX_MLIR_ENABLE_WRROR "Treat warnings as errors." OFF)`
`set(LLVM_ENABLE WERROR ${ONNX_MLIR_ENABLE_WERROR}`

**Comment by AlexandreEichenberger** [comment]
@etiotto is this issue ready to close?

**Comment by etiotto** [comment]
@AlexandreEichenberger not yet.

**Comment by sorenlassen** [comment]
with the recent removal compiler warnings since the upgrade to c++17 will it work to treat compiler warnings as errors from now on?

**Comment by sstamenova** [comment]
> with the recent removal compiler warnings since the upgrade to c++17 will it work to treat compiler warnings as errors from now on?

No, see https://github.com/onnx/onnx-mlir/pull/1627. There's more work to do first :)

**Comment by AlexandreEichenberger** [comment]
new issue to track this one: #2027
