### ISSUE TITLE
Changing policy on how we merge to master

### ISSUE THREAD

**Issue by AlexandreEichenberger** [onnx/onnx-mlir#955]
Currently, we force a successful CI run on the absolute latest version of master. This force us to serialize the merging of branches to master, with a 3h delay due to the WindowCI.

I am proposing that we switch to the same mode as LLVM. If a branch successfully run the CIs on the master branch, and the current approved branch can do a clean merge/rebase on the master, then we allow merging that branch to master without mandating a clean CI run on the latest master.

The drawback of this proposal is that there is a slight chance that although a branch did run cleanly on a (possibly older) master branch and can be merged cleanly on the current master, it may still fails the CI. Thus we need to
1. Check after merging that the CIs did compete successfully (this is done by going on the Code tab, and checking that the bubble next to your branch becomes green.
2. If the CIs on your branch fail, to revert your merge (and possibly the other merged branches committed after the failing merged branch, fix it as quickly as possible, get a successful run, and merge again.

Let us know how you feel about this proposal.

**Comment by sstamenova** [comment]
There are a couple of things that make this successful for LLVM:

1) There are buildbots that cover a lot of scenarios AND the buildbots send devs emails when they fail - so no "manual" step of checking status is required. No email = successful build, so no action needed

2) The buildbot owners (as well as the community at large) will deal with issues when a commit breaks the bots but the committer doesn't notice. This happens when there are multiple breaking changes in a row, for example. If a break persists "long enough", someone else might fix it or revert it when the committer hasn't taken action and the "someone else" is often the buildbot owner. This means that there will need to be someone ultimately responsible for the builds for onnx-mlir and making sure that the committers get pinged or offending changes get fixed or reverted.

The onnx-mlir community is much smaller at the moment, so there will be fewer cascading failures and probably fewer failures in genera. However, there will also be fewer people who notice failures and fix them when the committers are unavailable, so I expect that more of the fixing/reverting will fall on the build owners.

At the end of the day, I think either model can work well but you need to be aware that the build owners (who I assume will be the folks at IBM) will be taking on the additional work of making sure the build stays green.

**Comment by AlexandreEichenberger** [comment]
@sstamenova thanks for your thoughtful comments and your insight on the LLVM process.

If the WindowCI is down to a similar time as the others, probably waiting the 30 min or so to be sure that we have no issue by merging into the latest is probably going to be fine. Last week, we had a pileup of 10+ PR ready and folks were stopping to rebase because there was always someone else putting their changes first. Looking forward for the Window CI with LLVM caching, that should get us a long way to more manageable CI times.

We can also temporarily go to the LLVM mode if there are a lot of patches on documentations... which have no impact on the CIs.

**Comment by sstamenova** [comment]
@AlexandreEichenberger: There is a third option - I think (though I am not 100% sure) that there should be an option to have the CIs exclude certain files. For example, the Windows CI could run only if files other than the documentation files have been changed.

**Comment by sstamenova** [comment]
I looked at the documentation for Azure Pipelines ang GitHub, and I'm pretty sure there are a couple of simple improvements we can make to the CI flow on Windows (in addition to figuring out how to save llvm builds which we will do regardless). See https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml for more information.

1) We can exclude documentation based on file or directory
2) We can batch builds for commits to master (so if there is a running build, the next time it builds, it will include all commits made in the mean time)
3) Individual CIs can always skip validation with a special message in the commit (https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#skipping-ci-for-individual-commits)

Let me know if you think one or more of these would be useful.

**Comment by AlexandreEichenberger** [comment]
Thanks, @gongsu832 is also having the test going in parallel, he say that it also shave some time. That should work orthogonally with your suggestions.

For your 1 above, are you saying that we can ensure that changes to the docs (e.g. md files) and/or files under `doc/` does not need to have CI confirmation? Or are you saying that we can skip the `make check-docs` target?

I will defer on @gongsu832 to evaluate 2 and 3 above.

**Comment by gongsu832** [comment]
Looking at the time breakdown of Windows CI, the vast majority of time was spent on building llvm-project. Removing that would bring the Windows CI build time to be around 40-50 minutes, on par with the Linux Jenkins CIs. So I would refrain from making any changes until that is done, to avoid making an already fairly involved build system even more complicated.

**Comment by sstamenova** [comment]
> For your 1 above, are you saying that we can ensure that changes to the docs (e.g. md files) and/or files under `doc/` does not need to have CI confirmation? Or are you saying that we can skip the `make check-docs` target?

It is possible to tell the CI that changes to files in a directory, or with a certain extension, etc. should not trigger it at all.

Let's wait until the llvm builds are resolved to make these changes.

**Comment by AlexandreEichenberger** [comment]
Closing as this is now discussed in #1031
